language: go
go:
  - "1.11.2"
env:
  global:
  - GO111MODULE=on
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci