# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/logzio/logzio_terraform_client
    steps:
      - checkout
      - run: mkdir -p build
      - run: GO111MODULE=on go get -v -t ./...
      - run: GO111MODULE=on go build -o ./build/terraform-provider-logzio
  acceptance_test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/logzio/logzio_terraform_client
    steps:
      - checkout
      - run: GO111MODULE=on go get -v -t ./...
      - run: GO111MODULE=on TF_ACC=true go test -v ./...
workflows:
  version: 2
  build:
    jobs:
      - build
#  acceptance_test:
#    triggers:
#      - schedule:
#          cron: "0 0 * * *"
#          filters:
#            branches:
#              only:
#                - develop
#    jobs:
#      - acceptance_test